### ISSUE TITLE
Uncaught TypeError: Cannot read property 'tagName' of null

### ISSUE THREAD

**Issue by jamontoya** [awsp/handsontable-meteor#16]
Hi, 

I have a something like this

```
var Datablocks   = new Meteor.Collection(null);
...
function colorBlockRenderer(instance, td, row, col, prop, value, cellProperties) {
  Handsontable.renderers.TextRenderer.apply(this, arguments);

  Datablocks.find()
            .fetch()
            .forEach(function(elem, key){
              if ( elem.start &&
                  ((elem.start.row <= row) && (elem.end.row >= row)) &&
                  ((elem.start.col <= col) && (elem.end.col >= col))) {
                $(td).addClass(elem.cssClass);
              }
            });
}
...
Handsontable.renderers.registerRenderer('colorBlockRenderer', colorBlockRenderer);
...
  var options = {
    data                   : data,
    columns                : columns,
    rowHeaders             : true,
    colHeaders             : true,
    outsideClickDeselects  : false,
    manualColumnResize     : true,
    manualRowResize        : true,
    disableVisualSelection : 'area',
    cells: function (row, col, prop) {
      var cellProperties = {};

      cellProperties.renderer = "colorBlockRenderer"; // uses lookup map

      return cellProperties;
    },
  };

  hot = new Handsontable(container, options);


```

where start and end are like {row:number, col:number}, and cssClass is a string with a css class :) I add or remove objects from Datablocks based on user interaction...
it happen to me, sometimes when adding blocks to Datablocks, an error is shown in the console, not sure if the render is related ( I think not, but just in case I added) 

Uncaught TypeError: Cannot read property 'tagName' of null

![image](https://cloud.githubusercontent.com/assets/535053/11049250/b4da5d7a-8702-11e5-9f71-70fdffb09219.png)

Seems that the problem is a missing validation, but I just wanted to let you know
Regards
Jorge

**Comment by awsp** [comment]
Thanks for reporting!
Tho it looks like there is already a related issue reported.  
https://github.com/handsontable/handsontable/issues/2732

I would recommend tracking that issue instead. :-)
Closing this as this looks more likely on Handsontable issue instead.
