### ISSUE TITLE
using with ReactJS

### ISSUE THREAD

**Issue by dcsan** [awsp/handsontable-meteor#20]
thanks for packaging and publishing this!

I'm trying to use it with ReactJS and having some issues

I'm using the `componentDidMount` event, but sometimes the data is not ready at this point
loading when the data is ready, is also not reliable - I need to wait and init the table when the DOM is loaded AND the meteor data is ready.

Any thoughts on how to do that?

**Comment by awsp** [comment]
Thank you for using this package. 
As far as I am concerned, `componentDidMount` is an event used in ReactJS when DOM finishes loading and you definitely need to wait for Meteor's subscription to finish before loading your component. 

If you happen to use kadirahq's [Flow Router with React](https://atmospherejs.com/kadira/flow-router-ssr), a pretty famous package with Meteor, then you could do it pretty easily with their pre-written mixins.  I actually happened to fork their sample and you could take a look at [here](https://github.com/awsp/hello-react-meteor/blob/master/both/components/post_page.jsx). 

Also, you could initialize an empty Handsontable first and do a `loadData()` after. 
If you are not using that package, you could also take a look at this file, basically the actual mixin that `flow-router-ssr` is using. 

https://github.com/meteor/react-packages/blob/f68f682a14a0d49814c4a753ec9711f23595c34d/packages/react-meteor-data/meteor-data-mixin.jsx

Hope it helps!

**Comment by dcsan** [comment]
thanks! i got it working by putting calls to reload in a couple of places (render and getMeteorData) and avoid double calling with guards in the code.

**Comment by awsp** [comment]
Glad you get it work. Closing this issue.
