### ISSUE TITLE
Bundle handsontable-ruleJS plugin to add formula support

### ISSUE THREAD

**Issue by hluz** [awsp/handsontable-meteor#6]
Would be great if we could get formula support...

http://docs.handsontable.com/0.15.1/demo-formula-support.html

https://github.com/handsontable/handsontable-ruleJS

:-)

**Comment by awsp** [comment]
Yea, I was planning to add it, but due to some technical issue I haven't solved. It turns out I finally got it work! So now you can enable formula support. Hope you like it.  :D

Thanks for your comment and support on this package!

**Comment by hluz** [comment]
Whow!!! In less than 2 hours, and even pushed to Atmosphere!!!

Man. On the beach and kicking-ass! :+1:
